// Generated by AgentEX
// Build ID: {{BUILD_ID}}
// Generated: {{TIMESTAMP}}

import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

interface Message {
  role: "user" | "assistant";
  content: string;
}

interface AgentConfig {
  model: string;
  temperature: number;
  max_tokens: number;
  tools: any[];
}

const config: AgentConfig = {{AGENT_CONFIG}};

export async function runAgent(messages: Message[]) {
  try {
    const response = await anthropic.messages.create({
      model: config.model,
      max_tokens: config.max_tokens,
      temperature: config.temperature,
      messages: messages,
      tools: config.tools,
    });

    return response;
  } catch (error) {
    console.error("Agent error:", error);
    throw error;
  }
}

// API Route Handler (Next.js)
export async function POST(request: Request) {
  const { messages } = await request.json();
  
  const response = await runAgent(messages);
  
  return Response.json(response);
}
