import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { githubToken, repoName, files } = body

    if (!githubToken || !repoName || !files) {
      return NextResponse.json(
        { error: 'Missing required parameters' },
        { status: 400 }
      )
    }

    // Create repository
    const createRepoResponse = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Authorization': `token ${githubToken}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: repoName,
        description: 'Generated by AgentEX',
        private: false,
        auto_init: false,
      }),
    })

    if (!createRepoResponse.ok) {
      const error = await createRepoResponse.json()
      return NextResponse.json(
        { error: error.message || 'Failed to create repository' },
        { status: createRepoResponse.status }
      )
    }

    const repo = await createRepoResponse.json()
    const repoUrl = repo.html_url

    // Create files using GitHub Contents API
    // Note: This is a simplified version. In production, you'd need to:
    // 1. Create a commit with all files
    // 2. Handle large files
    // 3. Support multiple commits for large repos

    return NextResponse.json({
      success: true,
      repoUrl,
      message: 'Repository created successfully. Files can be pushed manually or via additional API calls.',
    })
  } catch (error: any) {
    console.error('GitHub export error:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to export to GitHub' },
      { status: 500 }
    )
  }
}
