# Generated by AgentEX
# Build ID: {{BUILD_ID}}
# Generated: {{TIMESTAMP}}

import os
from anthropic import Anthropic
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List

app = FastAPI()
client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))

class Message(BaseModel):
    role: str
    content: str

class AgentRequest(BaseModel):
    messages: List[Message]

# Agent configuration
AGENT_CONFIG = {{AGENT_CONFIG}}

@app.post("/agent")
async def run_agent(request: AgentRequest):
    try:
        response = client.messages.create(
            model=AGENT_CONFIG["model"],
            max_tokens=AGENT_CONFIG["max_tokens"],
            temperature=AGENT_CONFIG["temperature"],
            messages=[msg.dict() for msg in request.messages],
            tools=AGENT_CONFIG.get("tools", []),
        )
        
        return response
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
